// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ws = require("ws");
var Curry = require("rescript/lib/js/curry.js");

var sockets = [];

var webServer = new Ws.Server({
      port: 8080
    });

Curry._2(webServer.on, "connection", (function (socket) {
        return sockets.push(socket);
      }));

exports.sockets = sockets;
exports.webServer = webServer;
/* webServer Not a pure module */
